In [1]:
import numpy as np

#ЗАДАНИЕ №1

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#ЗАДАНИЕ №2

In [3]:
b1 = a.reshape(12, 1)
b1

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [4]:
b2 = a.reshape(6, 2)
b2

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [5]:
b3 = a.reshape(4, 3)
b3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [6]:
b4 = a.reshape(3, 4)
b4

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
b5 = a.reshape(2, 6)
b5

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

#ЗАДАНИЕ №3

In [8]:
c1 = a.reshape(12, -1)
c1

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [9]:
c2 = a.reshape(3, -1)
c2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
c3 = a.reshape(2, -1)
c3

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
c4 = a.reshape(-1, 3)
c4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [12]:
c5 = a.reshape(-1, 2)
c5

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

#ЗАДАНИЕ №4

###Массив NumPy из 1 столбца и 12 строк не льзя назвать одномерным, потому что он выводится с дополнительными [], что онаглядно видно из первых трех заданий. Таким образом массив из 1 столбца и 12 строк является двумерным.

#ЗАДАНИЕ №5

In [14]:
d = np.random.randn(3, 4)
print(d)
print(d.size)

[[ 0.59779008  1.33866575 -0.12514974  0.0245888 ]
 [-1.32515025  0.53845125 -2.40666288  1.36408055]
 [-0.35581503 -1.17071298 -0.55684118  0.01112972]]
12


In [15]:
d = d.flatten()
print(d)
print(d.size)

[ 0.59779008  1.33866575 -0.12514974  0.0245888  -1.32515025  0.53845125
 -2.40666288  1.36408055 -0.35581503 -1.17071298 -0.55684118  0.01112972]
12


#ЗАДАНИЕ №6

In [16]:
e = np.arange(20, 0, -2)
e

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#ЗАДАНИЕ №7

In [18]:
f = np.arange(20, 1, -2).reshape(1, 10)
f

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

##разница между массивами e и f в том, что e - это одномерный массив, а f - двумерный.

#ЗАДАНИЕ №8

In [19]:
g = np.zeros((2, 2))
g

array([[0., 0.],
       [0., 0.]])

In [20]:
h = np.ones((3, 2))
h

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
i = np.vstack((g, h))
print(i)
print(i.size)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
10


#ЗАДАНИЕ №9

In [24]:
j = np.arange(0, 12)
j

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
k = j.reshape(4, 3)
k

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
kt = k.transpose()
kt

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [32]:
l = np.dot(k, kt)
print(l)
print(l.shape)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
(4, 4)


In [33]:
l_inv = np.linalg.inv(l)
l_inv

LinAlgError: Singular matrix

Вычислить обратную матрицу не получится, потому что это сингулярная матрица

#ЗАДАНИЕ №10

In [57]:
import random
np.random.seed(42)
print(random.random())

0.04869475461467776


#ЗАДАННИЕ №11

In [35]:
n = np.random.randint(0, 16, 16)
n

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

#ЗАДАНИЕ №12

In [36]:
N = n.reshape(4, 4)
N

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [37]:
O = l + N * 10
O

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [41]:
O1 = np.linalg.det(O)
O1

-28511999.999999944

In [42]:
O2 = np.linalg.matrix_rank(O)
O2

4

In [43]:
O_inv = np.linalg.inv(O)
O_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

#ЗАДАНИЕ №13

In [44]:
O_inv = np.where(O_inv < 0, 0, 1)
O_inv

array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

In [45]:
print(l)
print(N)
P = np.where(O_inv == 1, l, N)
P

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])